export const productsList = [
	{ name: 'milk', category: 'dairy', foodProduct: true },
	{ name: 'bread', category: 'bakery', foodProduct: true },
	{ name: 'toothpaste', category: 'personal care', foodProduct: false },
	{ name: 'shampoo', category: 'personal care', foodProduct: false },
	{ name: 'notebook', category: 'office supplies', foodProduct: false },
	{ name: 'chicken', category: 'meat', foodProduct: true },
	{ name: 'eggs', category: 'dairy', foodProduct: true },
	{ name: 'orange juice', category: 'beverages', foodProduct: true },
	{ name: 'spaghetti', category: 'pantry', foodProduct: true },
	{ name: 'dish soap', category: 'household', foodProduct: false },
	{ name: 'laundry detergent', category: 'household', foodProduct: false },
	{ name: 'potatoes', category: 'produce', foodProduct: true },
	{ name: 'bananas', category: 'produce', foodProduct: true },
	{ name: 'cookies', category: 'snacks', foodProduct: true },
	{ name: 'toilet paper', category: 'household', foodProduct: false },
	{ name: 'yogurt', category: 'dairy', foodProduct: true },
	{ name: 'cereal', category: 'pantry', foodProduct: true },
	{ name: 'lettuce', category: 'produce', foodProduct: true },
	{ name: 'coffee', category: 'beverages', foodProduct: true },
	{ name: 'sandwich bags', category: 'household', foodProduct: false },
	{ name: 'soda', category: 'beverages', foodProduct: true },
	{ name: 'peanut butter', category: 'pantry', foodProduct: true },
	{ name: 'dishwasher detergent', category: 'household', foodProduct: false },
	{ name: 'facial tissues', category: 'household', foodProduct: false },
	{ name: 'frozen pizza', category: 'frozen', foodProduct: true },
	{ name: 'paper towels', category: 'household', foodProduct: false },
	{ name: 'canned soup', category: 'canned goods', foodProduct: true },
	{ name: 'olive oil', category: 'pantry', foodProduct: true },
	{ name: 'toothbrush', category: 'personal care', foodProduct: false },
 ];

